### ISSUE TITLE
Mixed plural case in container_type

### ISSUE THREAD

**Issue by kofalt** [scitran/api#129]
Recently, my understanding is that the `container_type` of a file object in the API did not have an `s` prefix, at least in the case of an `acquisition`. 

Thus, to generate a download URI (as I do in `jobs.py`) you add the s suffix:

`'/' + i['container_type'] + 's/' + i['container_id'] + '/files/' + i['filename']`

Surprisingly, this was not the case, as shown by these download URLs:

```
/acquisitionss/56a0159b6d7638bbbf9160d3/files/8892_nifti.nii.gz
/acquisitions/56a0159e6d7638bbbf9160f6/files/149_1_1_localizer.zip
```

It looks like spawning jobs from [listhandler post](https://github.com/scitran/api/blob/8dd87502b5d534205a618cc09be056ff70683523/api/handlers/listhandler.py#L401) will call `rules.create_jobs` with `acquisitions`.

I [added code](https://github.com/scitran/api/commit/802c53b99acb896ee115efd5305efde7cffa6b15) to jobs that throws an exception when called with plurals as a stopgap to limit the problem; here's a trace that hopefully illuminates the issue:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "./api/api.py", line 120, in dispatcher
    rv = router.default_dispatcher(request, response)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "./api/base.py", line 128, in dispatch
    return super(RequestHandler, self).dispatch()
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "./api/handlers/listhandler.py", line 401, in post
    rules.create_jobs(config.db, container, cont_name, file_properties)
  File "./api/rules.py", line 140, in create_jobs
    jobs.queue_job(db, alg_name, input)
  File "./api/jobs.py", line 108, in queue_job
    raise Exception('Container type cannot be plural :|')
```

**Comment by rentzso** [comment]
the issue is related to the create_jobs calls:
```rfrigato@axial:~/Projects/scitran/venv/api/api$ grep -r create_jobs *
core.py:                rules.create_jobs(config.db, container.acquisition, 'acquisition', fileinfo)
core.py:                rules.create_jobs(config.db, container.acquisition, 'acquisition', fileinfo)
handlers/listhandler.py:            rules.create_jobs(config.db, container, cont_name, file_properties)
rules.py:def create_jobs(db, container, container_type, file_):
```
in core is singular, in handlers/listhandler.py plural. @kofalt which do you prefer?

**Comment by rentzso** [comment]
As it seems a little urgent, I have pushed a commit that should fix the issue.
Feel free to reopen it if any other problem arises.

**Comment by kofalt** [comment]
Excellent, thanks! :+1:
