### ISSUE TITLE
Error when attempting sessions download

### ISSUE THREAD

**Issue by dpuccetti-flywheel** [scitran/api#92]
Some of the recent changes appear to have effected file downloads.  This was previously working.  The issue occurs when attempting to retrieve the ticket for the download.

Endpoint: /api/download
Method: POST
Payload:
```
{"optional":true,"nodes":[{"level":"session","_id":"5660680b9737e71a69dc8c4b"},{"level":"session","_id":"5660680c9737e71a69dc8c4f"}]}
```

Response Code: 500
Response:
```
<html>
 <head>
  <title>500 Internal Server Error</title>
 </head>
 <body>
  <h1>500 Internal Server Error</h1>
  The server has either erred or is incapable of performing the requested operation.<br /><br />



 </body>
</html>
```

Log entry:
```

2015-12-08 17:40:49             root               webapp2.py  1552:ERRO 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "./api/api.py", line 126, in dispatcher
    rv = router.default_dispatcher(request, response)
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "./api/base.py", line 125, in dispatch
    return super(RequestHandler, self).dispatch()
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/scitran/persistent/venv/local/lib/python2.7/site-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "./api/core.py", line 249, in download
    return self._preflight_archivestream(req_spec)
  File "./api/core.py", line 184, in _preflight_archivestream
    prefix = project['group'] + '/' + project['label'] + '/' + session.get('label', 'untitled')
TypeError: 'NoneType' object has no attribute '__getitem__'
[pid: 14428|app: 0|req: 60/137] 10.0.2.2 () {52 vars in 918 bytes} [Tue Dec  8 17:40:49 2015] POST /api/download => generated 228 bytes in 31 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)

```

**Comment by rentzso** [comment]
@dpuccetti-flywheel to facilitate debugging could you make sure you have a fresh install of the db?
Also, if you did some operations on a fresh db and then you've seen the issue, could you please send these operations?

**Comment by dpuccetti-flywheel** [comment]
Starting the environment fresh resolved the issue.  There must have been an issue with the db as you mentioned.
